### ISSUE TITLE
Migrate broken bintray `url`s in Casks

### ISSUE THREAD

**Issue by cho-m** [Homebrew/homebrew-cask#104924]
Casks with Bintray URLs are now broken since service is being shut down.
This issue is to track broken Casks along with their fixes, removal, or upstream tracker:
- [x] [`meshcommander`](https://formulae.brew.sh/cask/meshcommander)
- [x] [`sonic-visualiser`](https://formulae.brew.sh/cask/sonic-visualiser) - **DONE.** ~~Seen some CA cert issues https://github.com/Homebrew/homebrew-cask/issues/104924#issuecomment-830844709~~ CI didn't have issue in PR #104967
- [x] [`squirrel`](https://formulae.brew.sh/cask/squirrel) - **DONE.** ~~Need new upstream host https://github.com/rime/squirrel/issues/564~~ Cask URLs migrated in #105053
- [x] [`swift-explorer`](https://formulae.brew.sh/cask/swift-explorer) - **DONE.** Cask removed in #104925
- [x] [`tigervnc-viewer`](https://formulae.brew.sh/cask/tigervnc-viewer) - **DONE.** ~~Pending new upstream host https://github.com/TigerVNC/tigervnc/issues/1236~~ Migrate in #104966
- [x] [`vienna`](https://formulae.brew.sh/cask/vienna) - **DONE.** Cask URLs migrated in #104918

**Comment by cho-m** [comment]
For `sonic-visualiser`, there is another download URL, but Homebrew `curl` CA certificates has issue with site, which causes issues with various `brew` commands.

Example showing issue with Homebrew `curl` but working with Apple `curl`:
```console
❯ $(brew --prefix curl)/bin/curl "https://code.soundsoftware.ac.uk/attachments/download/2788/Sonic%20Visualiser-4.3.dmg"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

❯ /usr/bin/curl  "https://code.soundsoftware.ac.uk/attachments/download/2788/Sonic%20Visualiser-4.3.dmg"
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

**Comment by SMillerDev** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=code.soundsoftware.ac.uk&latest

The certificate chain is incomplete so I'm confused why macOS would work here.

**Comment by cho-m** [comment]
@SMillerDev Not too sure.
It could be difference between LibreSSL and OpenSSL.
Or behavior with different CA cert file.

This isn't the first Cask I saw this in.
Also saw similar CA cert issue in: https://github.com/Homebrew/homebrew-cask/pull/104677#issuecomment-828905366
And I think a few others.

Not too sure what is best way to deal with this.

**Comment by carlocab** [comment]
Do we use brewed `curl` for audits here in Cask? That's a surprise to me, because we use system `curl` for audits in Homebrew/core.

**Comment by cho-m** [comment]
@carlocab it actually might be system curl but difference in versions of macOS / LibreSSL.

I see that linked `fawkes` cask fails on 10.15 node, but running `audit` online works for me on local 11.3.
```console
❯ brew audit --online --cask fawkes
==> Downloading https://mirror.cs.uchicago.edu/fawkes/files/1.0/Fawkes-1.0.dmg
Already downloaded: ......
audit for fawkes: passed
```

I guess if there is actual certificate issues, then contacting upstream would be option.

**Comment by seff** [comment]
Squirrel has updated the download link. #https://github.com/rime/home/issues/701

**Comment by cho-m** [comment]
Thanks @seff. Created PR for updating that Cask.

---

With this, only one cask is left, but it may need input from Homebrew maintainers on best way to deal with `meshcommander`.

Can possibly:
- just leave dead URL and see if developer updates in future
- delete cask and let someone re-add if it is re-hosted.

Cask analytics:
```
 30 days =>   9
 90 days =>  32
365 days => 100
```

**Comment by cho-m** [comment]
Closing as done with migrating or removing Casks with Bintray URLs.

**Comment by carlocab** [comment]
Thanks @cho-m!
