### ISSUE TITLE
Convert `if MacOS.version` blocks to `on_system` blocks

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/homebrew-cask#137512]
### Description of issue

This is a tracking issue to monitor the progress of converting all `if MacOS.version` blocks into the new `on_system` blocks. We have better coverage with `brew readall` using these new blocks.

- [x] amethyst #137487
- [x] apparency #137516
- [x] appcleaner #137517
- [x] appgate-sdp-client #137518
- [x] araxis-merge #137536 
- [x] artisan #137537
- [x] bartender #137538
- [x] bbedit #137539 
- [x] birdfont #137625
- [x] boxcryptor #137626
- [x] calibre #137627
- [x] cave-story #137628
- [x] cd-to #137629
- [x] choosy #137630
- [x] clean-me #137631
- [x] cockatrice #137632
- [x] cocktail #137661 
- [x] contexts #137662 
- [x] controllermate #137803
- [x] copyq #137804
- [x] coteditor #137805
- [x] couchbase-server-enterprise #137807 
- [x] dash #137808 
- [x] datweatherdoe #137809 
- [x] day-o #137810 
- [x] deeper #137811 
- [x] diskmaker-x #137812 
- [x] drawpile #137813 
- [x] duet #137515
- [x] evernote #138309
- [x] f-bar #138310
- [x] far2l #138312
- [x] flrig #138311
- [x] fluor #138313 
- [x] freac #138314 
- [x] free-gpgmail #138315 
- [x] geekbench https://github.com/Homebrew/homebrew-cask/pull/138578
- [x] gobdokumente https://github.com/Homebrew/homebrew-cask/pull/138579
- [x] hammerspoon https://github.com/Homebrew/homebrew-cask/pull/138580
- [x] horos https://github.com/Homebrew/homebrew-cask/pull/138581
- [x] idefrag https://github.com/Homebrew/homebrew-cask/pull/138582
- [x] inkstitch https://github.com/Homebrew/homebrew-cask/pull/138583
- [x] ipartition https://github.com/Homebrew/homebrew-cask/pull/138584
- [x] ipsecuritas https://github.com/Homebrew/homebrew-cask/pull/138585
- [x] isubtitle https://github.com/Homebrew/homebrew-cask/pull/138586
- [x] isyncr https://github.com/Homebrew/homebrew-cask/pull/138587
- [x] iterm2 #138307 
- [x] itsycal #138034
- [x] jedit-omega https://github.com/Homebrew/homebrew-cask/pull/138588
- [x] jitouch https://github.com/Homebrew/homebrew-cask/pull/138589
- [x] karabiner-elements #138596 
- [x] klayout https://github.com/Homebrew/homebrew-cask/pull/138590
- [x] launchcontrol #137514
- [x] lingon-x #138618
- [x] linkliar https://github.com/Homebrew/homebrew-cask/pull/138597
- [x] liteicon https://github.com/Homebrew/homebrew-cask/pull/138598
- [x] macpilot https://github.com/Homebrew/homebrew-cask/pull/138599
- [x] maintenance https://github.com/Homebrew/homebrew-cask/pull/138600
- [x] max https://github.com/Homebrew/homebrew-cask/pull/138601
- [x] microsoft-auto-update https://github.com/Homebrew/homebrew-cask/pull/138602
- [x] microsoft-excel https://github.com/Homebrew/homebrew-cask/pull/138603
- [x] microsoft-outlook https://github.com/Homebrew/homebrew-cask/pull/138604
- [x] microsoft-powerpoint https://github.com/Homebrew/homebrew-cask/pull/138605
- [x] microsoft-word https://github.com/Homebrew/homebrew-cask/pull/138606
- [x] mkvtoolnix https://github.com/Homebrew/homebrew-cask/pull/138607
- [x] monitorcontrol #138619
- [x] monolingual https://github.com/Homebrew/homebrew-cask/pull/138608
- [x] mounty https://github.com/Homebrew/homebrew-cask/pull/138609
- [x] mysqlworkbench https://github.com/Homebrew/homebrew-cask/pull/138610
- [x] natron https://github.com/Homebrew/homebrew-cask/pull/138611
- [x] ncar-ncl https://github.com/Homebrew/homebrew-cask/pull/138612
- [x] nextcloud https://github.com/Homebrew/homebrew-cask/pull/138613
- [x] omnidisksweeper #137610
- [x] omnifocus #138124
- [x] omnigraffle https://github.com/Homebrew/homebrew-cask/pull/138614
- [x] omnioutliner https://github.com/Homebrew/homebrew-cask/pull/138615
- [x] omniplan https://github.com/Homebrew/homebrew-cask/pull/138616
- [x] omnipresence https://github.com/Homebrew/homebrew-cask/pull/138617
- [x] onyx #137513
- [x] openemu #137543
- [x] openttd #137544
- [x] orion #137490
- [x] playonmac #137949
- [x] powerphotos #138030
- [x] prismlauncher #138031 
- [x] proxifier #138032
- [x] qbittorrent #137664
- [x] reaper #137663
- [x] saoimageds9
- [x] secretive
- [x] sf-symbols
- [x] silentknight
- [x] simply-fortran
- [x] sip
- [x] sitesucker-pro
- [x] sourcetree
- [x] spideroakone
- [x] studiolinkstandalone
- [x] subsurface
- [x] suspicious-package #137611
- [x] teamspeak-client
- [x] teamviewer #137814 
- [x] touch-bar-simulator #138308 
- [x] tripmode
- [x] virtualhereserver
- [x] visit
- [x] vitamin-r
- [x] vpn-enabler
- [x] x2goclient

**Comment by Rylan12** [comment]
Thanks, everyone, for helping out with this!

I'll have a PR in homebrew/brew soon to enforce the `on_system` blocks

**Comment by bevanjkay** [comment]
@Rylan12 There's a few more in our other Homebrew-cask-* repos that might need attention, there's a couple of complicated ones in the drivers and versions repos.

**Comment by Rylan12** [comment]
I'm going to push forward, for now, to allow `HOMEBREW_INSTALL_FROM_API` to move forward (API installs aren't available for those repos right now, anyway) but I'll make sure to add a todo to hit all of these.

It looks like Homebrew/cask-drivers has 64 violations and Homebrew/cask-versions has 18.

**Comment by Rylan12** [comment]
Hmm, on second thought it might actually take more time to get the audit to be main-tap-specific so I might just start running through these. not sure yet

**Comment by bevanjkay** [comment]
@Rylan12 We can hit these next, especially if it's blocking the API project.
