### ISSUE TITLE
Tracking Objective-See apps

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#28165]
[Objective-See](https://objective-see.com/) apps are high-quality security apps for macOS. Some of them are apps to be run on demand, while others run continuously. These latter ones typically require a manual installer. In most cases that makes it impossible for us to automate their installation, and their uninstallation is suboptimal. I say “in most cases” because on some the developer was kind enough to provide a way to (un)install these from the CLI.

I’ve contacted the developer, as he said he will keep adding CLI (un)installers for the apps that are missing them, but that’ll likely only happen as new versions are released. That’s perfectly reasonable, but since we have no idea when that will happen for which, this issue is meant to track it as it happens.

### Cask that can be completely (un)installed via official CLI methods

- [x] [BlockBlock](https://objective-see.com/products/blockblock.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/blockblock.rb))
- [ ] [Ostiarius](https://objective-see.com/products/ostiarius.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ostiarius.rb)) [**Unlikely to happen**](https://github.com/caskroom/homebrew-cask/commit/2658ae14bb34c908739adccc1e84b5a7bf8e2eb4)
- [x] [OverSight](https://objective-see.com/products/oversight.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/oversight.rb))
- [ ] [What's Your Sign](https://objective-see.com/products/whatsyoursign.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/whatsyoursign.rb))
- [x] [KextViewr](https://objective-see.com/products/kextviewr.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/kextviewr.rb))
- [x] [KnockKnock](https://objective-see.com/products/knockknock.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/knockknock.rb))
- [x] [Lockdown](https://objective-see.com/products/lockdown.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/lockdown.rb))
- [x] [RansomWhere?](https://objective-see.com/products/ransomwhere.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ransomwhere.rb))
- [x] [TaskExplorer](https://objective-see.com/products/taskexplorer.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/taskexplorer.rb))
- [x] [Dylib Hijack Scanner](https://objective-see.com/products/dhs.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/dhs.rb))
- [x] [LuLu](https://objective-see.com/products/lulu.html) ([cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/lulu.rb))

**Comment by miccal** [comment]
List updated.

**Comment by miccal** [comment]
Note that [Dynamic Hijack Scanner](https://objective-see.com/products) is also called [Dylib Hijack Scanner](https://objective-see.com/products/dhs.html) and is available in Cask as [dhs.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/dhs.rb).

**Comment by vitorgalvao** [comment]
Updated the list again. Not that although we managed to fake What's Your Sign’s install, we’re still not using an official uninstallation method, and still can’t install automatically. As of now, RansomWhere? is the only persistent one of the bunch [that can do it](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ransomwhere.rb#L12L22).

**Comment by miccal** [comment]
Ah, of course - apologies.

**Comment by vitorgalvao** [comment]
Updated the list again. Since all of them are now present in HBC, it makes no sense to have that checkbox.

**Comment by commitay** [comment]
Updated the list with `lulu` https://github.com/caskroom/homebrew-cask/pull/38729
