### ISSUE TITLE
Roadmap to GPG verification

### ISSUE THREAD

**Issue by tapeinosyne** [Homebrew/homebrew-cask#5971]
As per #4688 and #4848, we intend to support GPG verification of cask packages in the form of an optional `gpg` stanza. This issue tracks the prerequisites of a working implementation. (Other relevant issues are #164, #1824.)

For those unfamiliar, GPG can verify the authenticity of a package, given:
- a file _signature_, offered by the package author, generally as a downloadable .sig or .asc file;
- a gpg _key_, either as a short-hand ID, or a downloadable .asc file.

To satisfy the requirements of GPG, it is necessary to download and store files which are not closely tied to our `url` stanza. As we lack such functionality, some work beyond `gpg` proper is required.
- [x] **Metadata** (#3066 #6117)  
  - Fetch and store the _signature_ in a persistent folder/file, which should not be deleted if `install` fails.
- [x] **Review Cask::DSL::Gpg** (#5975)  
  I would suggest to define the stanza as `gpg 'signature url', :key_type => 'key_value'`, which is shorter and arguably clearer than what we defined in #4848.
- [x] **GPG ops** (#6184)  
  - retrieve key from ID, or fetch from url;
  - verify package.
- [ ] **GPG interfaces**
  - core: wrap success/failure states, etc.
  - user-level: inform of gpg operations at install time.
- [ ] **Tests**
- [ ] **Docs**
- [x] **Add GPG stanza to compatible casks** (#6185)
- [x] Optionally, decouple checksum from `Cask::Download` (#5080)  
  Verification of integrity (via SHA-256) and authenticity (via GPG) could be moved to a dedicated module/class.
- [ ] Optionally, add generic download commands (#5080)  
  It might be desirable to introduce download methods which are not specific to cask `url`.

@caskroom/maintainers, I would appreciate feedback, particularly on the optional items which pertain to Cask's Ruby internals.

**Comment by olbrew** [comment]
Will this also work with GPG2? I only have that one installed as that is the [recommended version on the desktop](https://superuser.com/questions/655246/are-gnupg-1-and-gnupg-2-compatible-with-each-other).

**Comment by hellais** [comment]
From looking at all the related tickets, it seems like it has been decided that this should not be implemented.

Could somebody provide some background as to why it has been decided to drop this support for this?

cc @reitermarkus

**Comment by vitorgalvao** [comment]
> Could somebody provide some background as to why it has been decided to drop this support for this?

https://github.com/Homebrew/brew/pull/4120. Start at https://github.com/Homebrew/brew/pull/4120#issuecomment-406879969.
