### ISSUE TITLE
DSL 1.0 followups

### ISSUE THREAD

**Issue by rolandwalker** [Homebrew/homebrew-cask#7683]
These items have been bumped from DSL 1.0 roadmap #4688, which now contains only the items needed for merging metadata support.
- [ ] Cask followups
  - [x] relabel Cask tokens which start with numbers (#8002, #8018, homebrew-versions#607)
  - [x] enable commented-out `name` stanzas, main repo (#7978)
  - [x] `MacOS.release` switchover, all repos (#7982, caskroom/homebrew-versions#600)
  - [x] add more `name` stanzas, main repo
  - [x] enable `accessibility_access` stanzas, main repo (#7981)
  - [x] replace `#{self.name...}` hack in `caveats` with `#{token}`, all repos (#7979, caskroom/homebrew-versions#599)
  - [ ] seed `tags :vendor` values from `Info.plist`? (along with "auto-generated" comment?)
  - [x] seed `zap` stanzas from mackup and other sources  (#6174, #6609, #6863, #6899)
    - [x] one pass done (easy matches)
    - [x] could use another pass
  - [ ] seed `license` stanzas from GitHub projects with `LICENSE` files (#6645, #6693, #6633, many more todo)
- [ ] review `system_command` postflight
  - [ ] `CASK_LANGUAGE_REFERENCE.md`
  - [ ] `cask_language_deltas.md`
  - [ ] amend Casks, all repos
- [ ] test suite followups
  - [ ] various `depends_on` stubs
  - [ ] `conflicts_with` (all stubs)
  - [ ] `installer :script` (there is one test, but another would be good)
  - [ ] `installer :manual`
  - [ ] `uninstall :trash`
- [ ] backend followups
  - [ ] improve `suite` documentation
  - [ ] delete all backward-compat code not covered above: search code for
    - [ ] todo
    - [ ] temporary
    - [ ] transition
    - [ ] DSL
    - [x] fixme
    - [ ] removeme
    - [x] 0.50
    - [x] 1.0
    - [ ] backward
    - [x] forward
    - [x] deprecated
  - [ ] require `license` stanza (which may have value `:unknown`)
  - [ ] enforce all required stanzas per documentation
  - [ ] enforce at least one artifact per documentation
  - [ ] enforce new semantics
    - [ ] `app` should only take an app bundle
    - [ ] `suite` should take a directory, but not an app bundle
    - [ ] generic `artifact` should require `:target`
    - [ ] others?
  - [ ] require `uninstall`
    - [ ] may need `uninstall :none` for exceptional cases
    - [ ] require `uninstall` with `pkg`
    - [ ] require `uninstall` with `installer` (need to fix many Casks first)
  - [ ] refactor variables, methods, and classes as needed to match new forms
    - [x] `app` (#7065)
    - [x] `suite` (does not even have an associated class yet) (#7065)
    - [x] `artifact` (#7065)
    - [x] `link` (remove) (#7065)
    - [ ] `pkg`
    - [x] `preflight`, `postflight`, `uninstall_preflight`, `uninstall_postflight` (#7642)
    - [ ] `license`
    - [ ] `depends_on :formula`
    - [ ] other `depends_on` stubs
    - [ ] `conflicts_with` (all stubs)
    - [x] ~~`gpg`~~ (not altered)
    - [ ] `version :latest` as symbol
    - [x] ~~`zap`~~ (not altered)
    - [ ] `appcast` (new keys)
    - [ ] `installer :script`
    - [ ] `installer :manual`
    - [ ] `uninstall :delete`
    - [ ] `uninstall :trash`
    - [x] ~~`tags`~~ (not altered)
    - [ ] `container :type`
    - [ ] `container :nested` (more work than others: convert away from a pseudo-artifact)
      - [ ] `:nested_container` is also referenced in a Cask
    - [x] ~~`uninstall :rmdir`~~ (not altered)
    - [x] `token` (#7673)
  - [x] add `zap` verb (#6155)
    - [x] expand tilde in `:delete` values
    - [x] different treatment of relative paths in `:delete` (#6193)
    - [x] informative message when no `zap` stanza present (#6207)
  - [x] add `uninstall --force` (related to `zap` implementation) (#6208)
  - [ ] static Cask dumps
    - [ ] requires completing `container :nested` refactor, or applying workaround in the dump method
    - [ ] each form should provide `to_static` instead of `to_yaml`, returning a data structure which includes the stanza name
    - [ ] existing `_dump` verb should return full YAML structure instead of fragments
    - [ ] remove need to list dumpable forms twice (check Cask::DSL constants instead)
    - [ ] add JSON format
    - [ ] refactor dump so that setting debug flag is not needed
  - [ ] ability to search/filter/display tags
  - [ ] ability to search/filter/display licenses
  - [ ] implement dependencies
    - [ ] `depends_on :java`
    - [x] `depends_on :cask`
    - [ ] `conflicts_with :cask`
    - [ ] `conflicts_with :formula`
  - [ ] new verb `verify` which also covers gpg checks
  - [ ] `uninstall :trash` support
  - [ ] `launch` verb respecting `app`
  - [ ] `_appcast` verb which fetches and tests appcast checksums
  - [ ] expose version numbers extracted from `app` `Info.plist`
    - [ ] could be displayed in `ls --versions` (#5987)
  - [ ] command verbs `preflight`, `postflight`, `uninstall_preflight`, `uninstall_postflight`
    - [ ] new `--dry-run` option would be useful here
  - [ ] special treatment for `version :latest` symbol
    - [ ] cached downloads should expire quickly (#6087)

**Comment by jawshooah** [comment]
We should extract any useful items into their own issues and close this. @vitorgalvao, what do you think about this list?

**Comment by vitorgalvao** [comment]
@jawshooah On a first look through it, these seem to be what’s worth keeping:

- [ ] test suite followups
     - [ ] various `depends_on` stubs
     - [ ] `conflicts_with` (all stubs)
     - [ ] `installer :script` (there is one test, but another would be good)
     - [ ] `installer :manual`
     - [ ] `uninstall :trash`
- [ ] backend followups
     - [ ] improve `suite` documentation
     - [ ] delete all backward-compat code not covered above: search code for
         - [ ] todo
         - [ ] temporary
         - [ ] transition
         - [ ] DSL
         - [ ] removeme
         - [ ] backward
    - [ ] enforce at least one artifact per documentation
    - [ ] generic `artifact` should require `:target`
    - [ ] require `uninstall` with `pkg`
    - [ ] require `uninstall` with `installer` (need to fix many Casks first)
    - [ ] ability to search/filter/display licenses
    - [ ] implement dependencies
         - [ ] `depends_on :java`
         - [ ] `conflicts_with :cask`
         - [ ] `conflicts_with :formula`
    - [ ] new verb `verify` which also covers gpg checks
    - [ ] `uninstall :trash` support
    - [ ] `_appcast` verb which fetches and tests appcast checksums

Some of these may already have issues in place, but would have to check.

**Comment by josephholsten** [comment]
created #36821 to discuss potential impl of `_appcast` verb

**Comment by vitorgalvao** [comment]
@reitermarkus @claui This issue is outdated as hell, so I’m going to close. Pinging you as reference in case you feel it’s worth it to move something from [the list](https://github.com/Homebrew/homebrew-cask/issues/7683#issuecomment-167248256) to their own issues.

If you do but don’t want to make the issues yourselves, tell me which ones you’d like to see, and I’ll open them.
